version: '3.8'

services:
  avito-shop-service:
    build: .
    container_name: avito-shop-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      avito-db:
        condition: service_healthy
    networks:
      - avito-network


  avito-db:
    image: postgres:15.11-alpine3.21
    container_name: avito-db
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - avito-network

volumes:
  postgres_data:

networks:
  avito-network:
    driver: bridge